import type { Metadata } from 'next';
import Link from 'next/link';
import { LEGAL } from '@/lib/legal';
import { LegalPage, legalStyles as s } from '../legal/LegalPage';

export const metadata: Metadata = {
  title: `Privacy Policy — ${LEGAL.appName}`,
  description: `How ${LEGAL.appName} collects, uses, stores and deletes your personal data.`,
};

export default function PrivacyPolicyPage() {
  return (
    <LegalPage title="Privacy Policy">
      <p>
        This policy explains what personal data <strong>{LEGAL.appName}</strong> (the &ldquo;app&rdquo;,
        also available as a website) collects, why, who can see it, how long we keep it, and how you
        can have it deleted. The app is published by <strong>{LEGAL.developerName}</strong>{' '}
        (&ldquo;we&rdquo;, &ldquo;us&rdquo;).
      </p>

      <h2>1. What the app does</h2>
      <p>
        {LEGAL.appName} is a tournament-management platform. Organizers create events, players
        register for them, referees run bouts, and players receive brackets, results, ID cards and
        certificates.
      </p>

      <h2>2. Data we collect</h2>
      <table className={s.table}>
        <thead>
          <tr>
            <th>Data</th>
            <th>Who provides it</th>
            <th>Why</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Name, email address, password (stored only as a salted hash), role</td>
            <td>All users, at sign-up</td>
            <td>Create and secure your account; sign you in</td>
          </tr>
          <tr>
            <td>Date of birth, gender, state, district, phone, emergency-contact number</td>
            <td>Players</td>
            <td>Check age/weight-category eligibility, route registrations to the right district/state
              secretary, contact you or your emergency contact about an event</td>
          </tr>
          <tr>
            <td>Weight and weight-verification records</td>
            <td>Players and organizers</td>
            <td>Place players in the correct weight category</td>
          </tr>
          <tr>
            <td>NSRD ID</td>
            <td>Players (optional)</td>
            <td>Identify the player in the sport federation&rsquo;s records</td>
          </tr>
          <tr>
            <td>Aadhaar number (12 digits)</td>
            <td>Players (optional)</td>
            <td>Identity verification for events that require it. Kept in a separately restricted
              table, readable only by you and platform administrators, and never shown back in the
              app or website.</td>
          </tr>
          <tr>
            <td>Profile photo</td>
            <td>Users (optional)</td>
            <td>Your ID card and profile. Kept in a private storage bucket, readable only by you and
              platform administrators.</td>
          </tr>
          <tr>
            <td>Event registrations, attendance, bout results, brackets, certificates</td>
            <td>Generated by your participation</td>
            <td>Run the tournament and issue results and certificates</td>
          </tr>
          <tr>
            <td>Crash and error reports (device model, OS version, app version, error trace)</td>
            <td>Collected automatically by the app</td>
            <td>Find and fix bugs. These reports are not used for advertising.</td>
          </tr>
        </tbody>
      </table>
      <p>
        <strong>Camera.</strong> Organizers and referees can use the device camera to scan QR codes
        for attendance. Camera images are processed on the device to read the code and are not
        recorded or uploaded.
      </p>
      <p>
        We do <strong>not</strong> collect your location, contacts, microphone recordings, or
        advertising identifiers, and we do not show ads.
      </p>

      <h2>3. Who can see your data</h2>
      <ul>
        <li>You can see and edit your own profile.</li>
        <li>
          The organizer, referees and (where relevant) district or state secretary of an event you
          register for can see the registration details needed to run that event, such as your name,
          age, weight category, district and contact details.
        </li>
        <li>
          Platform administrators can access account data to support users and keep the platform
          secure.
        </li>
        <li>Certificates and results you receive may show your name, event and result.</li>
      </ul>
      <p>We do not sell your personal data and we do not share it with advertisers.</p>

      <h2>4. Service providers</h2>
      <p>We use these providers to run the service. They process data only on our behalf:</p>
      <ul>
        <li>
          <strong>Supabase</strong> &mdash; database, authentication and file storage.
        </li>
        <li>
          <strong>Sentry</strong> &mdash; crash and error reporting.
        </li>
        <li>
          <strong>Vercel</strong> &mdash; hosting of the website.
        </li>
        <li>
          <strong>Expo / EAS</strong> &mdash; delivery of app updates.
        </li>
      </ul>
      <p>Data is transmitted over encrypted (HTTPS/TLS) connections.</p>

      <h2>5. How long we keep data</h2>
      <p>
        We keep your account data while your account is active. If you ask us to delete your account
        (see <Link href="/account-deletion">Account &amp; data deletion</Link>), we delete or anonymize it
        as described on that page. Crash reports are kept for a limited period by our error-reporting
        provider.
      </p>

      <h2>6. Your choices and rights</h2>
      <ul>
        <li>Correct your details from the profile screen of the app or website.</li>
        <li>
          Request a copy of your data, correction, or deletion by emailing{' '}
          <a href={`mailto:${LEGAL.contactEmail}`}>{LEGAL.contactEmail}</a>.
        </li>
        <li>
          Request deletion of your account and data at any time &mdash; see{' '}
          <Link href="/account-deletion">Account &amp; data deletion</Link>.
        </li>
      </ul>

      <h2>7. Children</h2>
      <p>
        Players may be under 18. Where a player is a minor, the account should be created and managed
        by a parent or guardian, who may exercise the rights above on the minor&rsquo;s behalf. We do
        not knowingly collect data from a child without a parent or guardian&rsquo;s involvement; if
        you believe we have, contact us and we will delete it.
      </p>

      <h2>8. Security</h2>
      <p>
        Access to data is restricted by role using database-level access rules. Sensitive identifiers
        such as Aadhaar are kept in separately restricted storage. No system is perfectly secure; if a
        breach affecting you occurs we will notify affected users and the authorities as required by
        law.
      </p>

      <h2>9. Changes to this policy</h2>
      <p>
        If we change this policy we will update the effective date above and, for material changes,
        notify users in the app.
      </p>

      <h2>10. Contact</h2>
      <div className={s.callout}>
        <p>
          <strong>{LEGAL.developerName}</strong>
        </p>
        <p>
          Email: <a href={`mailto:${LEGAL.contactEmail}`}>{LEGAL.contactEmail}</a>
        </p>
        <p>We aim to respond to privacy requests and complaints within {LEGAL.deletionDays} days.</p>
      </div>
    </LegalPage>
  );
}
